on: 
  issues:
    types: [opened, edited, labeled, unlabeled]

jobs:
  deploy:
    if: contains(github.event.issue.labels.*.name, 'TBR') == false
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          ref: gh-pages
      - uses: actions/setup-node@v1
      - name: create a jekyll post from an issue
        uses: yoshum/issue-to-jekyll-post@v0
        with:
          post_dir: "_posts"
          update_filename: true
          timezone: Asia/Tokyo
          layout: post
      - env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          USER_EMAIL: ${{ secrets.EMAIL_ADDRESS }}
        run: |
          git config user.name yoshum
          git config user.email "${USER_EMAIL}"
          remote_repo="https://${ACCESS_TOKEN:-"x-access-token:$GITHUB_TOKEN"}@github.com/${GITHUB_REPOSITORY}.git"
          git remote set-url origin $remote_repo
          git add .
          git commit -m "add a post"
          git push origin ${BRANCH}
